### ISSUE TITLE
Question: client notifications

### ISSUE THREAD

**Issue by gerbil** [adobe/k8s-shredder#176]
**How** does shredder notifies clients that they are running workloads on parked nodes so that they can take proper actions ?

**Comment by adriananeci** [comment]
In our case, clients pods that are running on parked nodes are labeled too during the cluster upgrade process when worker nodes are rotated. 
We are labelling their pods with something like `shredder.ethos.adobe.net/upgrade-status=parked` and they are using the `kube_pod_labels ` kube state metrics for detecting if their pods ar running on a parked node or not.
