### ISSUE TITLE
About > Opinionated vs Oppinionated :) 

### ISSUE THREAD

**Issue by bryanlatten** [adobe/k8s-shredder#55]
### Expected Behaviour
Wrong spelling of opinionated

### Actual Behaviour
Right spelling of opionated

### Reproduce Scenario (including but not limited to)

<img width="357" alt="Screenshot 2023-05-19 at 10 52 16 AM" src="https://github.com/adobe/k8s-shredder/assets/1202354/183bf1e4-1a6b-4d77-b639-851f958c2dc3">

#### Steps to Reproduce
N/A

#### Platform and Version
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by aalexandru** [comment]
It's just an opionated way of spelling opionated :)

**Comment by jrsapi** [comment]
I can tell by the commit it's almost Hacktoberfest.
